name: ~create summary for an entire workflow run

on:
  workflow_call:

jobs:
  action:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Write output to step summary
        shell: bash -x -e {0}
        run: |
          find -name "sitrep.json" | while read -s f; do
            cat "$f" | jq -r '.summary' | tee -a $GITHUB_STEP_SUMMARY
          done

      # - name: Concatenate all sitreps
      #   shell: bash -x -e {0}
      #   run: |
      #     # combine all sitreps files into a single file, where each sitrep json sits
      #     # in a field named by the folder that contained it

      #     find -name "sitrep.json" | while read -s f; do
      #       echo "$(dirname $f): $(cat $f)," >> 
      #     done
