name: CI

on:
  push:
  #   branches: [ "main" ] 
  pull_request:
  #   branches: [ "main" ]
  
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: |
          set -x
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          RUN_NUMBER=`printf "%08d" $GITHUB_RUN_NUMBER`
          CONTAINER_REPO=`echo ${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE="${CONTAINER_REPO}:${RUN_NUMBER}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          tags: ${{ env.IMAGE }}
          file: Dockerfile.jax
          build-args: |
            BASE_IMAGE=nvidia/cuda:12.1.0-runtime-ubuntu20.04

  jax-unit-tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: List GPUs
        run: |
          hostname
          date
          nvcc --version
          nvidia-smi -L
          nvidia-smi

      - name: Print environment variables
        run: |
          set -x
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          RUN_NUMBER=`printf "%08d" $GITHUB_RUN_NUMBER`
          CONTAINER_REPO=`echo ${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE="${CONTAINER_REPO}:${RUN_NUMBER}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        run: |
          docker run ${{ env.IMAGE }} nvidia-smi -L

