name: Nightly Distribution test
run-name: Nightly Distribution test (${{ github.event_name == 'workflow_run' && format('nightly {0}', github.event.workflow_run.created_at) || github.event_name }})

on:
  workflow_dispatch:
  workflow_run:
    workflows: [~Sandbox]
    types: [completed]
    branches: [dynamic-names]

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows

jobs:

  test-distribution:
    uses: ./.github/workflows/_test_distribution.yaml
    secrets: inherit

  if-upstream-failed:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') && github.event_name != 'workflow_dispatch'
    steps:
      - run: echo 'Upstream workflow failed, aborting run' && exit 1
